### ISSUE TITLE
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.     at ChatInputCommandInteraction.followUp 

### ISSUE THREAD

**Issue by uniktron** [uzox/uzox#17]
All Bot commands work without any issues. Any time that I request to play a song or playlist I get the error,

> uzox@3.0.0 start
> NODE_ENV=production node .

[Thu Mar 02 2023 12:02:02] Launched shard 0
Mongoose connected
Logged in as BOT-NAME#1784 on Shard ID 0
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (/home/username/code/uzox/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:184:64)
    at Object.execute (/home/username/code/uzox/src/commands/music/play.js:27:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleNewInteraction (/home/username/code/uzox/src/handlers/interaction.js:32:21)
    at async Client.<anonymous> (/home/username/code/uzox/src/bot/bot.js:52:51) {

I filled up al the config.json file with the information requested with the exception of "MICROSERVICES_API": "https://uzox.xyz/api/",.  I don't know where to get that. I cant ping point where this one is firing up from. Any help or idea how can I fix it?

**Comment by Moquent** [comment]
uzox.xyz/api is the correct one, but that error is probably due to an old update, will have to update the code soon. until then it won't work, you can try updating it yourself too. check the pull requests, one of them has potential fixes for this.

**Comment by uniktron** [comment]
Ok I will try. Thank you for getting back to me. Appreciate it.
