### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Swapeii28** [uzox/uzox#4]
hey i have been trying to run the bot but its showing me this error . 
code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/uzox/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uzox-2.2@2.2.1 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uzox-2.2@2.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-02T09_10_46_925Z-debug.log
exit status 1


**Comment by Moquent** [comment]
Try installing the modules first using the `npm install` command

**Comment by Swapeii28** [comment]
what is the version of node.js is required for the bot to work ?

**Comment by Moquent** [comment]
Node.js 16<

**Comment by Swapeii28** [comment]
[Tue Nov 02 2021 15:32:51] Launched shard 0
G:\Users\Swapnil\Downloads\uzox-main\uzox-main\src\bot\bot.js:51
    new SpotifyPlugin({
    ^

**TypeError: SpotifyPlugin is not a constructor**
    at Object.<anonymous> (G:\Users\Swapnil\Downloads\uzox-main\uzox-main\src\bot\bot.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
G:\Users\Swapnil\Downloads\uzox-main\uzox-main\node_modules\discord.js\src\sharding\Shard.js:158
        reject(new Error('SHARDING_READY_DIED', this.id));
               ^

Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (G:\Users\Swapnil\Downloads\uzox-main\uzox-main\node_modules\discord.js\src\sharding\Shard.js:158:16)
    at Object.onceWrapper (node:events:510:26)
    at Shard.emit (node:events:390:28)
    at Shard._handleExit (G:\Users\Swapnil\Downloads\uzox-main\uzox-main\node_modules\discord.js\src\sharding\Shard.js:394:10)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  [Symbol(code)]: 'SHARDING_READY_DIED'
}

Node.js v17.0.1

**Comment by Swapeii28** [comment]
sorry for bothering you again

**Comment by Swapeii28** [comment]
where do we put bot's client id and client secrete ?

**Comment by Moquent** [comment]
You don't

**Comment by Swapeii28** [comment]
SyntaxError: G:\Users\Swapnil\Downloads\uzox-main (1)\uzox-main\config\config.json: Unexpected token { in JSON at position 580
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1161:22)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (G:\Users\Swapnil\Downloads\uzox-main (1)\uzox-main\index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)

Node.js v17.0.1
i have added you on discord it would be more convenient if you could reply there . Lets fix this code

**Comment by Moquent** [comment]
Feel free to join our support server, https://uzox.tech/support

**Comment by Moquent** [comment]
Hope your issue was fixed in our DMs
